Local test functions, Github CI, and additional package
beacon-biosignals/PyOnda pull request #1
Opened 2023-08-10 11:36 UTC by MKVatinyan

2023-08-11 12:44 UTC, MKVatinyan commented
some additional changes may be needed to publish the package to PyPi, it can maybe be handled later, what do you think ?

2023-08-21 12:54 UTC, AntoineGuillot2 requested changes
If possible, It would be nice:
- to decouple the file download from the pyarrow/numpy logic. This should remove some codes duplicate
- use moto tomock S3 and avoid relyng on S3 buckets.

2023-08-21 12:54 UTC, AntoineGuillot2 commented on src/pyonda/utils.py
> +            dataframe[schema_field] = dataframe[schema_field].map(list)
It may be nice to have warnings/errors when you encounter Legolas Schemas that the package does not support.

2023-08-21 12:54 UTC, AntoineGuillot2 commented on src/pyonda/load.py
> +def load_lpcm_zst_file_from_s3(file_url, sample_type, n_channels):
perhaps use dtype instead of sample_type for consisentensy for numpy and other python packages ?

2023-08-21 12:54 UTC, AntoineGuillot2 commented on src/pyonda/load.py
> +    return np.ndarray(buffer = file_buf.getbuffer(), dtype = sample_type, shape = (n_channels, full_length // n_channels), order='F')
1) Could this work for a 1-liner ?
`np.frombuffer(file_buf.getbuffer(), dtype=sample_type).reshape(n_channels,-1)`

2) A clear error message should be raised if the length of the array is not a multiple of n_channels.

2023-08-21 12:54 UTC, AntoineGuillot2 commented on src/pyonda/utils.py
> +            dataframe[schema_field] = dataframe[schema_field].map(list)
You can be restrictive and only allows schemas that are defined in Legolas ?

2023-08-21 12:54 UTC, AntoineGuillot2 commented on tests/test_load.py
> +    pd.testing.assert_frame_equal(df, load_arrow_table(signal_arrow_table_path))
If we want to test the default argument, this mays be simpler:
https://stackoverflow.com/questions/12627118/get-a-function-arguments-default-value

2023-08-21 12:54 UTC, AntoineGuillot2 commented on tests/test_load.py
> +        "Loaded arrow table is not as expected"
For mocking S3, moto is nice. 
http://docs.getmoto.org/en/latest/docs/getting_started.html

2023-08-21 12:54 UTC, AntoineGuillot2 commented on tests/test_utils.py
> +
Relying on moto may be more unit-testy

2023-08-21 12:54 UTC, AntoineGuillot2 commented on src/pyonda/load.py
> +def load_lpcm_zst_file(path_to_file, sample_type, n_channels):
Perhaps use dtype instead of sample_type for consisentensy for numpy and other python packages ?

2023-08-21 12:54 UTC, AntoineGuillot2 commented on src/pyonda/load.py
>          if True apply arrow_to_processed_pandas to loaded table, by default True
To decouple the S3 logic from the reading logic and remove some duplicate code:
- load_arrow_table_from_buffer
- load_arrow_table_from_file (which calls load_arrow_table_from_buffer)
- load_arrow_table_from_s3 (which calls load_arrow_table_from_buffer)

Similarly for LPCM files, I would decouple things a bit more.

2023-08-21 15:19 UTC, MKVatinyan commented on src/pyonda/load.py
> +    return np.ndarray(buffer = file_buf.getbuffer(), dtype = sample_type, shape = (n_channels, full_length // n_channels), order='F')
i still need to get the full_length value so it could work with your one liner but it just comes down to replacing a line by another line

```
    full_length = len(np.frombuffer(buffer.getbuffer(), dtype=dtype))
    if full_length // n_channels != full_length / n_channels:
        raise ValueError(f'n_channels ({n_channels}) not a multiple of array length ({full_length})')
    return np.frombuffer(buffer.getbuffer(), dtype=dtype).reshape(n_channels,-1, order="F")
```

2023-08-21 16:31 UTC, MKVatinyan commented on src/pyonda/load.py
> +    return np.ndarray(buffer = file_buf.getbuffer(), dtype = sample_type, shape = (n_channels, full_length // n_channels), order='F')
i guess the better way is this to avoid double frombuffer
```
    data = np.frombuffer(buffer.getbuffer(), dtype=dtype)
    full_length = len(data)
    if full_length // n_channels != full_length / n_channels:
        raise ValueError(f'n_channels ({n_channels}) not a multiple of array length ({full_length})')
    return data.reshape(n_channels,-1, order="F")
```

2023-08-22 08:10 UTC, AntoineGuillot2 commented on src/pyonda/load.py
> +    return np.ndarray(buffer = file_buf.getbuffer(), dtype = sample_type, shape = (n_channels, full_length // n_channels), order='F')
Instead of this: `if full_length // n_channels != full_length / n_channels:`it may be clearer to check that the remainder of the euclidian division is zero ? `full_length % n_channels == 0`

2023-08-22 08:51 UTC, MKVatinyan commented on tests/test_load.py
> +        "Loaded arrow table is not as expected"
I feel like the only difference would be working with a mock bucket instead of the actual ci bucket and the code would be the same no ?

2023-08-22 08:53 UTC, AntoineGuillot2 commented on tests/test_load.py
> +        "Loaded arrow table is not as expected"
Yes and the test file would be included in the GH repo instead of S3

2023-08-22 13:09 UTC, MKVatinyan commented on src/pyonda/utils.py
> +            dataframe[schema_field] = dataframe[schema_field].map(list)
are you saying it's better to redesign this to check the schema in the opened arrow table and add processings per schema ? (so have unsupported/supported ones)
because here any arrow table can be opened, nothing is unsupported, it's juste if there are non python data types in the table, loading can result in some weird columns (like the uuid case)

2023-08-22 13:19 UTC, AntoineGuillot2 commented on src/pyonda/utils.py
> +            dataframe[schema_field] = dataframe[schema_field].map(list)
Yes, if they are non-standard python data types and we do not have a preprocessing, it would be better to raise. 
 Otherwise, it may lead to data in the table that is not formatted properly (the UUIDs are a good example of what happens if we do not have a preprocessing).

2023-08-23 15:08 UTC, AntoineGuillot2 approved these changes

2023-08-23 15:08 UTC, merged