Update pyarrow to pandas processing function
beacon-biosignals/PyOnda pull request #18
Opened 2024-01-08 08:42 UTC by MKVatinyan

- [ ] Add check on time span contents unit (need to be nanoseconds)
- [ ] Add creation of a start and stop columns from the span column 
- [ ] Add deletion of the span column
- [ ] Adapt all related tests
- [ ] Bump version

2024-03-25 15:11 UTC, AntoineGuillot2 requested changes

2024-03-25 18:04 UTC, a-cakir commented on src/pyonda/utils/processing.py
> +            ]
maybe a check like the one from below

```
   if (
            "ARROW:extension:name" in metadata.keys()
            and metadata["ARROW:extension:name"] == "JuliaLang.UUID"
        ):
```

is possible?

2024-03-25 18:04 UTC, a-cakir commented on tests/data/test.onda.signal_processed.csv
> +eeg,"['fp1', 'f3', 'c3', 'p3', 'f7', 't3', 't5', 'o1', 'fz', 'cz', 'pz', 'fp2', 'f4', 'c4', 'p4', 'f8', 't4', 't6', 'o2']",microvolt,1.0,-1.0,float32,128.0,176ecfcf-d4c7-49ba-adec-f338d0a0c01f,/home/
looks like these are seconds. We should keep this as nanoseconds

2024-03-25 18:04 UTC, a-cakir commented on tests/utils/test_processing.py
> +    df = to_pandas_with_workaround_for_list_of_uuids(table, my_schema)
can we add tests for the contents of this dataframe

2024-03-26 09:23 UTC, MKVatinyan commented on src/pyonda/utils/processing.py
> +def to_pandas_with_workaround_for_list_of_uuids(table, table_schema):
i mean, this is the clearest one i could think of haha, you have another idea ?

2024-03-26 09:53 UTC, MKVatinyan commented on src/pyonda/utils/processing.py
> +    dataframe["stop"] = dataframe["span"].map(lambda x: x["stop"].seconds)
> Seconds is a float here or are we selecting the number of seconds?
so my code is incorrect here first of all, this is what happens basically 
```python
>>> t1 = pa.array([562346000000], type=pa.duration('ns'))
>>> t1
<pyarrow.lib.DurationArray object at 0x7f83fa055280>
[
  562346000000
]

>>> t1[0]
<pyarrow.DurationScalar: Timedelta('0 days 00:09:22.346000')>

>>> t2 = t1.to_pandas()[0]
>>> t2
Timedelta('0 days 00:09:22.346000')

>>> t2.seconds
562 # incorrect

# this is how it should go
>>> t2.total_seconds() * 1e9
562346000000.0
```

> we want nanoseconds, no?

yes there is no real reason to convert to seconds here

i did this because in our private project we convert to seconds but i can leave nano here, and we can keep the conversion in our project if necessary

2024-03-26 10:43 UTC, MKVatinyan commented on src/pyonda/utils/processing.py
> +    dataframe["stop"] = dataframe["span"].map(lambda x: x["stop"].seconds)
keeping as ns

2024-03-26 14:41 UTC, MKVatinyan commented on src/pyonda/utils/processing.py
> +                lambda x: [str(uuid.UUID(y)) for y in x] if x is not None else x
```python
>>> import uuid
>>> uuid.UUID("blabla")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/homebrew/Cellar/python@3.9/3.9.18_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/uuid.py", line 177, in __init__
    raise ValueError('badly formed hexadecimal UUID string')
ValueError: badly formed hexadecimal UUID string
```

2024-03-26 14:59 UTC, MKVatinyan commented on src/pyonda/utils/processing.py
> +            ]
i have this `check_if_schema_field_has_unsupported_binary_data` function that checks that all `FixedSizeBinaryType` fields are associated with the metadata mentioned above

2024-03-29 17:31 UTC, AntoineGuillot2 approved these changes

2024-03-29 17:31 UTC, AntoineGuillot2 commented on src/pyonda/utils/processing.py
> +            )
What happens if this is a list of something that is not a FixedSizeBinary?

2024-03-29 17:31 UTC, AntoineGuillot2 commented on src/pyonda/utils/processing.py
> +            )
This feel weird if the unit is already nanosecond?

2024-03-29 17:31 UTC, AntoineGuillot2 commented on tests/data/test.onda.signal_processed.csv
> +ecg,"['avl', 'avr']",microvolt,0.25,0.0,int16,128.0,bf11f8f0-36a4-4ef6-b339-9b4f98f72af2,/home/ubuntu/repositories/data/onda_tour_data/bf11f8f0-36a4-4ef6-b339-9b4f98f72af2_ecg.lpcm.zst,lpcm.zst,ecg,"
Can you add tests with nanoseconds that cannot be converted to seconds represented as integer ? (ie that are not divisible by 1e9)

2024-03-29 17:31 UTC, AntoineGuillot2 commented on src/pyonda/utils/processing.py
> +            dst_entries.append(dst_entry)
That part may be very slow if we have a lot of rows (we are iterating on rows when building dst_entry?)

2024-04-02 08:53 UTC, MKVatinyan commented on src/pyonda/utils/processing.py
> +            )
if list it goes in the first l84-l86 part, then each element is tested, if it's not a binary nothing happens

2024-04-02 08:54 UTC, MKVatinyan commented on src/pyonda/utils/processing.py
> +            )
x['start'] and x['stop'] are internally converted to a timedelta object, i cannot extract nanoseconds directly, hence these operations

2024-04-02 08:56 UTC, MKVatinyan commented on src/pyonda/utils/processing.py
> +            dst_entries.append(dst_entry)
yes we are, and yes it probably will be, if it's a problem we can tackle in a follow up

2024-04-02 15:35 UTC, merged