add utilities to create julia compatible arrow tables
beacon-biosignals/PyOnda pull request #2
Opened 2023-10-23 09:01 UTC by MKVatinyan

Add function to reverse python uuid bytestring
Add function to create Onda.annotation like schema
Add function to create a TimeSpan like struct

2023-10-23 09:38 UTC, AntoineGuillot2 reviewed
Is it possible to add tests to check that the objects can be read in Julia? Does it add too much complexity? 
If it's too complex for now, it may be a nice to have in the future

2023-10-23 09:38 UTC, AntoineGuillot2 commented on tests/utils/test_schemas.py
> +    assert TimeSpan._fields == ('start', 'stop')
You can also check the values of the fields

2023-10-23 09:38 UTC, AntoineGuillot2 commented on src/pyonda/utils/schemas.py
> +    )
Do we need a function there ? Or does an immutable variable do the job ?

2023-10-23 10:26 UTC, MKVatinyan commented on src/pyonda/utils/schemas.py
> +    )
how do you document an immutable variable ?

2023-10-23 12:46 UTC, AntoineGuillot2 commented on src/pyonda/utils/schemas.py
> +    )
Does this work for you?
https://stackoverflow.com/questions/20227051/how-to-document-a-module-constant-in-python

2023-10-23 14:04 UTC, MKVatinyan commented on src/pyonda/utils/schemas.py
> +    )
proposed solution is sphinx to extract comments as documentation, this won't give like hover documentation if you import this somewhere else, you will need to go to the website

+ the idea of this is to get the schema and potentially append fields to it

I don't really see the upside of using a variable ?

2023-10-23 14:05 UTC, MKVatinyan commented
> Member

https://beacon-biosignals.slack.com/archives/C0618CY9PEH/p1698058125577519

2023-10-23 16:33 UTC, AntoineGuillot2 commented on src/pyonda/utils/schemas.py
> +    )
This is not a function, so it may makes more sense from a logical standpoint to have a CONSTANT.
But I am fine with the function too.

2023-10-23 17:00 UTC, AntoineGuillot2 requested changes

2023-10-23 17:00 UTC, AntoineGuillot2 commented on src/pyonda/save_arrow.py
> +    return upload_status
We need a try/finally statement here to ensure the file is deleted whatever happens

2023-10-23 17:00 UTC, AntoineGuillot2 commented on src/pyonda/save_lpcm.py
> +    return upload_status
Same regarding the try/finally or a context manager around the temporary directory.

2023-10-23 17:00 UTC, AntoineGuillot2 commented on src/pyonda/save_lpcm.py
> +    return upload_status
Try/except to delete the file if the upload raise.

2023-10-23 17:00 UTC, AntoineGuillot2 commented on src/pyonda/utils/s3_upload.py
> +    return True
Do we have a good reason to catch the error here ?

2023-10-23 17:00 UTC, AntoineGuillot2 commented on tests/test_save_lpcm.py
> +    assert np.array_equal(saved_data, expected_data)
The tests here will raise if there is an issue on the load array from s3.
Can you generate the data in-memory and check that expected data == data in memory ?

2023-10-23 17:00 UTC, AntoineGuillot2 commented on tests/test_save_lpcm.py
> +    assert np.array_equal(saved_data, expected_data)
Similarly here, having the data in-memory would ensure that the test only tests the save_array_function

2023-10-23 17:00 UTC, AntoineGuillot2 commented on tests/utils/test_schemas.py
> +
It may be nice to add a test to ensure that floating values raise

2023-10-24 13:38 UTC, MKVatinyan commented on src/pyonda/save_arrow.py
> +    return upload_status
```python

2023-10-24 13:40 UTC, MKVatinyan commented on src/pyonda/utils/s3_upload.py
> +    return True
not really, just copy pasted the code from the link

2023-10-24 15:13 UTC, MKVatinyan commented on src/pyonda/save_arrow.py
> +    return upload_status
https://stackoverflow.com/questions/61264374/using-tryfinally-without-except-never-generates-any-error

2023-10-25 08:33 UTC, AntoineGuillot2 approved these changes

2023-10-25 09:05 UTC, merged